#!/usr/bin/python

a=[]
a.append("media Mujahideen")
a.append("Media Alblattform")
a.append("Media Zahra")
a.append("Al-Qaeda in the Islamic Maghreb")
a.append("Islamic awakening forum")
a.append("inform the hosts of the Islamic state.")
a.append("Islamic state.")
a.append("Mujahideen Shura Council.")
a.append("mujahideen")
a.append("black")
a.append("Jihad")
a.append("infidel")
a.append("martyrdom")
a.append("Hear us if you want fairness.")
a.append("jihad of the arbitration law.")
a.append("Muhammad and his companions state of Islam.")
a.append("loyalty to the Muslims and disavowal of the infidels.")
a.append("Report")
a.append("#Daash")
a.append("another explosive device")
a.append("Islamic Caliphate")
a.append("killed and injured")
a.append("death to the west")
a.append("brothers")
a.append("puppets")
a.append("media Mujahideen")
a.append("Media Alblattform (swivel")
a.append("Media Alblattform")
a.append("Media Zahra")
a.append("Al-Qaeda in the Islamic Maghreb")
a.append("Al-Qaeda in the Islamic Maghreb: Media Andalusia")
a.append("rule: forum redemption")
a.append("rule: Youth Media")
a.append("rule: Media greeting")
a.append("female partisans of the youth movement.")
a.append("Youth: Media battalions (Islamic State Branch)")
a.append("Ansar al-Islam: Media Wing")
a.append("Ansar al-Sharia (Tunisia)")
a.append("AQAP inspirational magazine")
a.append("Islamic Army in Iraq: News Buraq")
a.append("Islamic awakening forum")
a.append("inform the hosts of the Islamic state.")
a.append("Islamic state: Media sit")
a.append("Islamic State News in the state of Anbar")
a.append("Islamic State: News mandate of Diyala")
a.append("Islamic State: Gaza Division")
a.append("Islamic state.")
a.append("Islamic State: News mandate of tenderness")
a.append("Islamic State: News mandate of southern Iraq.")
a.append("Front victory: Media insight")
a.append("Front victory: white lighthouse: the state of Idlib")
a.append("Army of the Nation in the environs of Jerusalem: Media Ensign")
a.append("Army of the Nation in the environs of Jerusalem: News Lair mujahideen")
a.append("studios Jundallah")
a.append("Saraya Ashtar: Islamic Resistance in Bahrain.")
a.append("Mujahideen Shura Council.")
a.append("forum Hmokh Islam.")
a.append("Taliban: Solo emirate")
a.append("moving the Taliban - Pakistan")
a.append("moving the Taliban - Pakistan: media age.")
a.append("Islamic Party of Turkestan: the voice of Islam.")
a.append("mujahideen")
a.append("black")
a.append("Jihad")
a.append("infidel")
a.append("martyrdom")
a.append("# Aftaas")
a.append("# Ala_tahin")
a.append("# To Aah_briqh")
a.append("# To Aah_vzan")
a.append("# To Aah_tarabuls")
a.append("# To Aah_tkirc")
a.append("# To Aah_alriqh")
a.append("# Dolh_alkhlavh")
a.append("# To Aah_khrsan")
a.append("# To Aah_albarakh")
a.append("# To Aah_djlh")
a.append("# Shiites")
a.append("I swear to you, the same Tensln to Tensln or Tlnh that bring")
a.append("P to make for the sake of God.")
a.append("Hear us if you want fairness.")
a.append("jihad of the arbitration law.")
a.append("Ibn Taymiyyah mosque")
a.append("God Njani thanks massacre")
a.append("under the Islamic Caliphate Adamha of God.")
a.append("Lord certificate in your path.")
a.append("We would stay here.")
a.append("j arithmetic III")
a.append("Tomorrow we meet Valentines")
a.append("Muhammad and his companions state of Islam.")
a.append("Emirate of Iraq - where the wrestler men.")
a.append("loyalty to the Muslims and disavowal of the infidels.")
a.append("spoke and I just hit what you can.")
a.append("Your words are alive and remain silent inanimate")